### ISSUE TITLE
Reverse an Ecommerce transaction  if we cancel order

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-google-ecommerce-analytics#2]
Very nice to have opportunity Reverse an Ecommerce transaction if we cancel order.

https://www.optimizesmart.com/how-to-remove-modify-google-analytics-ecommerce-transaction-in-one-click/
https://www.optimizesmart.com/reverse-ecommerce-transaction-google-analytics/
https://support.google.com/analytics/answer/1037443?hl=en

**Comment by Andrew-Orlov** [comment]
https://github.com/VirtoCommerce/vc-module-google-ecommerce-analytics/releases/tag/v1.0.1
